### PR TITLE
Update 1.2.11.1

### PR DESCRIPTION
**Pull request by ekomarova**

### CODE REVIEW

**Comment by ekomarova** [comment]
@remkade

**Comment by remkade** [comment]
Hi @ekomarova , thanks for the help! I don't think we want to move away from the official sources for this. Is there something you are hoping to fix by updating to `1.2.11.1`?

**Comment by AndresGuzman-Ballen** [comment]
@remkade Hi there! The reason 1.2.11.1 is being used is because a while back, we found that 1.2.11 was blacklisted for security reasons and that we needed to use 1.2.11.1. I can try to get more details since I currently do not have them (since like I said, this was a while back).

**Comment by ekomarova** [comment]
Hi @remkade , This PR has been open for a long time. Is there a chance that it will be merged?

**Comment by remkade** [comment]
We rarely use unofficial sources that deviate from upstream. My concern is that these changes don't appear to have been upstreamed to the main zlib project. Do you know the status of bugfixes from the `zlib` project side?

We'll discuss internally if this is something we want to do.

**Comment by AndresGuzman-Ballen** [comment]
@remkade I remember another engineer telling me zlib is no longer being maintained (notice how it hasn't been touched since January 2017): https://zlib.net/. Someone else (I believe within Intel) forked it and added security patches to it. This is how IntelPython is able to distribute zlib without having to worry about exposing users to security vulnerabilities.

**Comment by AndresGuzman-Ballen** [comment]
@remkade I will get back to you; I want to make sure my information is accurate :)

**Comment by AndresGuzman-Ballen** [comment]
@remkade Thanks for your patience! We looked further into this and it turns out that although zlib has not officially put out a new version since 1.2.11, they still do make updates in their develop branch, so I was wrong in stating that the madler/zlib project is no longer supported.

At the time, we were told that this zlib was blacklisted and that we needed to use jtkukunas/zlib but this happened years ago, and I don't remember the exact reason it was blacklisted. It's not obvious now; there are no CVE's that exist with zlib that could be the reason for it, and the sources differ quite significantly (since the jtkukunas is also a different implementation of zlib). Because of this, I do not believe I have a case for why Anaconda should merge this PR.

@ekomarova can you close this PR and make note that we will continue to build zlib with the whitelisted sources?

**Pull request closed without merging**
